### ISSUE TITLE
Scrap Brain Act 3; Missing Moving Platform

### ISSUE THREAD

**Issue by AmeBleu** [ElspethThePict/S1Forever#14] opened 2024-10-13 01:12 UTC
In Scrap Brain Act 3 at the topmost path there is a platform that shows up only in a level editor, but strangely not the actual game. Even then, if it was added back into the game, it would need it's physics tweaked as to not fall into the water and to match the Mega Drive original.

Missing Platform
![Screenshot (51)](https://github.com/user-attachments/assets/ae26f609-2897-43cc-90ca-334a95132e66)

Level editor
![Screenshot (53)](https://github.com/user-attachments/assets/bb4bdab0-cd5e-4d25-963c-1c933d68ff9c)

Original game
![Screenshot (56)](https://github.com/user-attachments/assets/93fbe390-1379-4656-b701-11b1e15f07d4)

Readded to the stage
![Screenshot (52)](https://github.com/user-attachments/assets/f3867eed-a97e-4f29-9e26-3756b7e2b3f5)

**Comment by ElspethThePict** [comment] 2024-10-13 07:31
Hi, thanks for the report.

May I ask, how did you re-add the platform if it was already appearing in the editor?

**Comment by ElspethThePict** [comment] 2024-10-13 19:18
Looking deeper into this issue and it seems this block never appears in normal play. Once the camera gets left of 0x0A00 the block despawns, never to return. Reaching this point of the level without doing that is impossible without debug mode.

The block doesn't appear in the level in Forever as it is programmed with the logic used in Labyrinth Zone act 1; it appears only when the correct button has been pressed. This is also why it follows the water line. That is behaviour we added to the LZ1 block.

An interesting bit of trivia but not a bug, so we won't be fixing it.

**Closed by ElspethThePict** 2024-10-13 19:18 UTC
